### ISSUE TITLE
jupyter notebook

### ISSUE THREAD

**Issue by lucjan78** [Netflix/sureal#5]
Hi,

I tried to run the code in jupyter notebook but I get such error:
```python
import matplotlib.pyplot as plt
import numpy.random as rn
import numpy as np
import scipy.stats as stat

import sys 
# please update
sys.path.append('your path')

import sureal
from sureal.config import SurealConfig, DisplayConfig
from sureal.tools.misc import import_python_file
from sureal.dataset_reader import RawDatasetReader, SyntheticRawDatasetReader, MissingDataRawDatasetReader, SelectSubjectRawDatasetReader, CorruptSubjectRawDatasetReader, CorruptDataRawDatasetReader
from sureal.subjective_model import MosModel, MaximumLikelihoodEstimationModel, SubjrejMosModel, ZscoringSubjrejMosModel
from sureal.routine import run_subjective_models
from sureal.tools.decorator import persist_to_file
```
Error is:
```
Traceback (most recent call last):

  File "/home/lucjan/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-494c8aa0b319>", line 13, in <module>
    from sureal.subjective_model import MosModel, MaximumLikelihoodEstimationModel, SubjrejMosModel, ZscoringSubjrejMosModel

  File "/home/lucjan/Dropbox/Projekty/SAM/sureal/python/src/sureal/subjective_model.py", line 96
    lambda (content_id, is_refvideo):
           ^
SyntaxError: invalid syntax
```

**Comment by JohnhqWang** [comment]
It seems to be a Python version problem. http://www.diveintopython3.net/porting-code-to-python-3-with-2to3.html#tuple_params
I would suggest to change your notebook kernel to Python 2.7
