### ISSUE TITLE
Missing Tkinter dependency note

### ISSUE THREAD

**Issue by Qub3k** [Netflix/sureal#6]
I just installed vanilla Ubuntu 18.04 LTS. Following the wiki I tried to issue "./run_subj". When doing so I got the following output:

```
Traceback (most recent call last):
  File "./run_subj", line 9, in <module>
    from sureal.routine import run_subjective_models
  File "/home/jakub/Workspace/sureal/python/src/sureal/routine.py", line 2, in <module>
    from matplotlib import pyplot as plt
  File "/home/jakub/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/jakub/.local/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/home/jakub/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/home/jakub/.local/lib/python2.7/site-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/home/jakub/.local/lib/python2.7/site-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/home/jakub/.local/lib/python2.7/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/home/jakub/.local/lib/python2.7/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package
```
I believe it would be beneficial to mention in the wiki that the Tkinter module is necessary to run this code.

**Comment by li-zhi** [comment]
This might be a platform-dependent issue. We are working toward packaging/publishing sureal as a pypi package. Hopefully the issue is going away after that.

**Comment by Qub3k** [comment]
It is possible that it is a platform-dependent issue. In my case it is even more complicated because I had to install the Ubuntu 18.04 LTS Server version, which is stripped of all GUI-related packages. That may be the problem.

**Comment by slhck** [comment]
I've created a PR for this.
